/* This file is auto-generated using the IRQN tool. Do not modify. */

#ifndef IRQN_HANDLER

#include <stm32f0xx_it.h>

#else

IRQN_HANDLER(-14, NonMaskableInt_IRQn)
IRQN_HANDLER(-13, HardFault_IRQn)
SKIP_HANLDER(-12)
SKIP_HANLDER(-11)
SKIP_HANLDER(-10)
SKIP_HANLDER(-9)
SKIP_HANLDER(-8)
SKIP_HANLDER(-7)
SKIP_HANLDER(-6)
IRQN_HANDLER(-5, SVC_IRQn)
SKIP_HANLDER(-4)
SKIP_HANLDER(-3)
IRQN_HANDLER(-2, PendSV_IRQn)
IRQN_HANDLER(-1, SysTick_IRQn)
IRQN_HANDLER(0, WWDG_IRQn)
IRQN_HANDLER(1, PVD_VDDIO2_IRQn)
IRQN_HANDLER(2, RTC_IRQn)
IRQN_HANDLER(3, FLASH_IRQn)
IRQN_HANDLER(4, RCC_CRS_IRQn)
IRQN_HANDLER(5, EXTI0_1_IRQn)
IRQN_HANDLER(6, EXTI2_3_IRQn)
IRQN_HANDLER(7, EXTI4_15_IRQn)
IRQN_HANDLER(8, TSC_IRQn)
IRQN_HANDLER(9, DMA1_Channel1_IRQn)
IRQN_HANDLER(10, DMA1_Channel2_3_IRQn)
IRQN_HANDLER(11, DMA1_Channel4_5_6_7_IRQn)
IRQN_HANDLER(12, ADC1_COMP_IRQn)
IRQN_HANDLER(13, TIM1_BRK_UP_TRG_COM_IRQn)
IRQN_HANDLER(14, TIM1_CC_IRQn)
IRQN_HANDLER(15, TIM2_IRQn)
IRQN_HANDLER(16, TIM3_IRQn)
IRQN_HANDLER(17, TIM6_DAC_IRQn)
IRQN_HANDLER(18, TIM7_IRQn)
IRQN_HANDLER(19, TIM14_IRQn)
IRQN_HANDLER(20, TIM15_IRQn)
IRQN_HANDLER(21, TIM16_IRQn)
IRQN_HANDLER(22, TIM17_IRQn)
IRQN_HANDLER(23, I2C1_IRQn)
IRQN_HANDLER(24, I2C2_IRQn)
IRQN_HANDLER(25, SPI1_IRQn)
IRQN_HANDLER(26, SPI2_IRQn)
IRQN_HANDLER(27, USART1_IRQn)
IRQN_HANDLER(28, USART2_IRQn)
IRQN_HANDLER(29, USART3_4_IRQn)
IRQN_HANDLER(30, CEC_CAN_IRQn)
IRQN_HANDLER(31, USB_IRQn)

#endif

